import Head from 'next/head';
import Image from 'next/image';
import Button from '../components/Button/Button';
import styles from '#styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button onClick={() => window.alert('hello')}>
        Do Something
      </Button>
    </div>
  )
}
